---
- name: "IP DINAMICAS"
  hosts: localhost
  remote_user: root
  vars_prompt:
    - name: "ip_dinamica"
      prompt: "ingrese la ip de un nuevo equipo"
      private: no
  tasks:
     - add_host:
         name: "{{ ip_dinamica }}"
         groups: dinamic-ip
       register: new_ip
     - debug: msg="{{ new_ip }}"
