---
- hosts: all
  remote_user: root
  vars:
    - tower_path: /tmp/ansible-tower-last-release
    - tower_admin_pass: admin-password
    - rhn_username: user-rhn
    - rhn_pass: "password-rhn"
    - hostname_full: host-id-rhn
    - count: 3
    - ip:192.168.0.1
  vars_prompt:
    - name: "ip_dinamica"
      prompt: "ingrese la ip de un nuevo equipo"
      private: no
  task:
     - add_host: "{{ ip_dinamica }}"
       groups: dinamic-ip

     - debug: msg=" cosas a realizar en este host"
